import type { Request, Response, NextFunction } from "express";

export function visitedEndpointsLogger(
  req: Request,
  _: Response,
  next: NextFunction
) {
  console.log(
    "Reqested Url: ",
    req.originalUrl,
    ": Generated By IP :",
    req.ip,
    ": time : ",
    new Date().toLocaleDateString() + " | " + new Date().toLocaleTimeString()
  );
  next();
}
