name: CI

on:
  pull_request: 
    branches: [main]
  
jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Check formatting with prettier
        run: npm run format:check

  linting:
    name: Lint code
    runs-on: ubuntu-latest
    needs: format

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.0
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check linting with eslint
        run: npm run lint

    # here will be test

  security:
    name: Check Security
    runs-on: ubuntu-latest
    needs: [format, linting]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.0
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Check for Vulnerabilities
        run: npm audit --production --audit-level=high